apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: distilbert-app
  namespace: flux-system
spec:
  interval: 5m
  path: "./flux-config/apps/distilbert"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system